### PR TITLE
Adding peter to the project

### PR DESCRIPTION
**Pull request by PeterBell**

### CODE REVIEW

**Comment by geraldini** [comment]
@PeterBell Fix indentation and commit :+1:

**Comment by PeterBell** [comment]
Hey @geraldini - done. Is this good?

**Comment by geraldini** [comment]
Looks great, @PeterBell !

**Comment by PeterBell** [comment]
Hey @geraldini could you give me a :+1: ?

**Comment by geraldini** [comment]
:+1:

**Comment by chang2020** [comment]
Let's :ship: it :+1:

**Pull request merged**
